#!/bin/bash

# exit immediately on errors
set -e
# error out if uninitialized variable is used
set -u

# Configuration Variables:
#
# GLOBAL / USER:
#
# job_directory - location of job files
# lvm_snapshotadd - Amount (in GiB) to add to the LV when doing the snapshot
# lvm_thinflag - (possibly not needed), 'true' if LV is a "thin" LV
# lvm_vgname - Volume Group name which contains the LV (optional)
# minimum_free_space - Measured in GiB (gigabytes), error if target has less, warn at 2x or less
# minimum_free_inodes - Error if target file system has less, warn at 2x or less
# usb_base - directory where USB backup drives are mounted
# usb_prefix - space delimited list of letters/numbers used as prefixes
# usb_filename - the unchanging portion of the mount directory
# usb_suffix - space delimited list of letters/numbers used as suffixes
# verbosity - 0=none, 1=some info, 2=debug level
#
# JOB SPECIFIC:
#
# backup_dir - Backup directory
# lvm_lvname - Logical Volume name of the backup_base directory (optional)

declare -a GlobalConfigVariables=( 
  'job_directory' 
  'lvm_snapshotadd' 'lvm_thinflag' 'lvm_vgname' 
  'minimum_free_space' 'minimum_free_inodes' 
  'usb_base' 'usb_prefix' 'usb_filename' 'usb_suffix' 
  'verbosity'
  );
declare -a JobSpecificVariables=( 
  'backup_dir' 
  'lvm_lvname' 
  );
AllVariables=("${GlobalConfigVariables[@]}" "${JobSpecificVariables[@]}")

# Set default values
backup_dir=""
job_directory="examples/"
lvm_lvname=""
lvm_snapshotadd=10
lvm_thinflag=true
lvm_vgname=""
minimum_free_space=25
minimum_free_inodes=50000
usb_base="/mnt/"
usb_prefix=""
usb_filename="BACKUP"
usb_suffix="1 2 3 4 5 6 7 8 9"
verbosity=2

if [ "$verbosity" -ge "2" ]; then
  echo "Default Configuration Variables:"
  for DefaultVariableName in ${AllVariables[@]}; do
    eval VerboseListVariableDefaultValue=\$$DefaultVariableName
    echo "  ${DefaultVariableName}=${VerboseListVariableDefaultValue}"
  done
  echo ""
fi

GlobalConfigFilename="defaults/sync2usb.conf"
UserConfigFilename="~/.sync2usb.conf"

function trim()
{
    local var=$1;
    var="${var#"${var%%[![:space:]]*}"}";   # remove leading whitespace characters
    var="${var%"${var##*[![:space:]]}"}";   # remove trailing whitespace characters
    echo -n "$var";
}

# read a configuration file
# $1 - filename (full path)
read_config_file () 
{
  echo "Reading config file: $1"
  if test -f "$1"; then 
    echo "The File Exists";
    while read line; do
      if [[ "$line" =~ ^[^#]*= ]]; then
        setting_name=$(trim "${line%%=*}");
        setting_value=$(trim "${line#*=}");
        echo 'found:' ${setting_name}'='${setting_value}
        case "$setting_name" in
          backup_dir)
            backup_dir="${setting_value}"
            ;;
          job_directory)
            job_directory="${setting_value}"
            ;;
          lvm_lvname)
            lvm_lvname="${setting_value}"
            ;;
          lvm_snapshotadd)
            lvm_snapshotadd="${setting_value}"
            ;;
          lvm_thinflag)
            lvm_thinflag="${setting_value}"
            ;;
          lvm_vgname)
            lvm_vgname="${setting_value}"
            ;;
          minimum_free_space)
            minimum_free_space="${setting_value}"
            ;;
          minimum_free_inodes)
            minimum_free_inodes="${setting_value}"
            ;;
          usb_base)
            usb_base="${setting_value}"
            ;;
          usb_prefix)
            usb_prefix="${setting_value}"
            ;;
          usb_filename)
            usb_filename="${setting_value}"
            ;;
          usb_suffix)
            usb_suffix="${setting_value}"
            ;;
          verbosity)
            verbosity="${setting_value}"
            ;;
          *)
            echo "WARN: ${setting_name} is not a valid configuration variable."
            ;;
        esac;
      fi
    done < "$1";
  else
    echo "Did not find config file: $1"
  fi
}

read_config_file ${GlobalConfigFilename}
read_config_file ${UserConfigFilename}

