#!/bin/bash

# report a configuration error
# $1 = setting name
# $2 = value of the attempted setting
# $3 = message
function config_error()
{
  echo ""
  echo "CONFIG ERROR: $1"
  echo ""
  echo "$2=$3"
  echo "  $4"
  echo ""
}

