#!/bin/bash

# lists all configuration variables and values to stdout
function list_variables ()
{
if [ "$verbosity" -ge "2" ]; then
  echo "$1"
  for VariableName in ${AllVariables[@]}; do
    echo "  ${VariableName}=${!VariableName}"
  done
  echo ""
fi
}
