#!/bin/bash

# save all the config variables prior to
# loading and executing a job file
function push_config_variables ()
{
for VariableName in ${AllVariables[@]}; do
  echo "${!VariableName}"
done
}

