#!/bin/bash

# save all the config variables prior to
# loading and executing a job file
function push_config_variables ()
{
#echo "push Configuration to SavedConfiguration"
for idx in "${!Configuration[@]}"; do
    SavedConfiguration[$idx]=${Configuration[$idx]}
done
}

