#!/bin/bash

shuffle_JobFiles() {
  local i tmp size max rand

  # $RANDOM % (i+1) is biased because of the limited range of $RANDOM
  # Compensate by using a range which is a multiple of the array size.
  size=${#JobFiles[*]}
  max=$(( 32768 / size * size ))

  if [ "${Configuration[verbosity]}" -ge "2" ]; then echo "Pre-Shuffle JobFiles:"; printf "%s\n" "${JobFiles[@]}"; fi
  for ((i=size-1; i>0; i--)); do
    while (( (rand=$RANDOM) >= max )); do :; done
    rand=$(( rand % (i+1) ))
    tmp=${JobFiles[i]} JobFiles[i]=${JobFiles[rand]} JobFiles[rand]=$tmp
  done
  if [ "${Configuration[verbosity]}" -ge "2" ]; then echo "Post-Shuffle JobFiles:"; printf "%s\n" "${JobFiles[@]}"; fi
}

