#!/bin/bash

# remove leading/trailing whitespace characters
function trim()
{
    local var=$1;
    var="${var#"${var%%[![:space:]]*}"}";
    var="${var%"${var##*[![:space:]]}"}";
    echo -n "$var";
}

